# Generated by Django 3.2.7 on 2021-10-03 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateField(verbose_name='Начало срока')),
                ('end_data', models.DateField(verbose_name='Конец срока')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бюджет пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('date_opened', models.DateField(auto_now_add=True, null=True, verbose_name='Дата открытия категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CategoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='Цвет в 16-ти ричной системе')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_name', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма операции')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к операции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='look.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='look.color', verbose_name='Цвет категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='look.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='look.categorytypes', verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='BudgetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='look.budget', verbose_name='Бюджет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='look.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('look.operation',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('look.operation',),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'color', 'name')},
        ),
    ]
